name: AI Validation POC

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Success Step
        run: echo "Hello from CI/CD"

      - name: Fail Step
        run: exit 1